In [258]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = raw_df.values[1::2, 2]

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\HP\AppData\Local\Temp\ipykernel_23456\3358670259.py:5: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


In [259]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [261]:
ml_model=LinearRegression()

# using a function

In [273]:
def get_linear_model(X,y):
    ml_model =LinearRegression()
    X_train,X_test,y_train,y_test=train_test_split(X,y)
    ml_model.fit(X_train,y_train)
    y_pred=ml_model.predict(X_test)
    score = r2_score(y_test,y_pred)
    mse=mean_squared_error(y_test,y_pred)
    print(f"Score: {score*100}\nMSE: {mse}")
    print(ml_model.coef_)
    print(ml_model.intercept_)


In [279]:
X_crim_rm_dis=X[:,[0,5,7]]
get_linear_model(X_crim_rm_dis,y)

Score: 63.44600591362672
MSE: 31.54075555775517
[-0.3432089   8.09576106 -0.04067506]
-26.913876628294965


In [277]:
x_age_b_tax=X[:,[6,11,9]]
get_linear_model(x_age_b_tax,y)

Score: 31.862640016268628
MSE: 54.30224583539627
[-0.04917555  0.01715825 -0.01613079]
26.53281579270935


In [283]:
x_indus_rad_lstat=X[:,[2,7,12]]
get_linear_model(x_indus_rad_lstat,y)

Score: 52.401195976735046
MSE: 49.354267038976715
[-0.27460291 -1.28060727 -1.00151679]
42.98301473776422


In [287]:
x_nox_rm_ptratio=X[:,[4,5,10]]
get_linear_model(x_nox_rm_ptratio,y)

Score: 61.676796686370615
MSE: 34.760440349091695
[-16.31543455   7.01265043  -1.14374932]
8.463576061310619


In [291]:
x_age_dis_rad=X[:,[6,7,8]]
get_linear_model(x_nox_rm_ptratio,y)

Score: 58.57844771441094
MSE: 27.18859945552436
[-15.37083523   7.89285083  -1.08042408]
1.630506569409878


## using Loop and a function

In [295]:
feature_combos=[X_crim_rm_dis,x_age_b_tax,x_indus_rad_lstat,x_nox_rm_ptratio,x_age_dis_rad]


In [301]:
for i in range(len(feature_combos)):
    a=get_linear_model(feature_combos[i],y)
    print(a)
    

Score: 68.96008936562616
MSE: 22.597226990184904
[-0.25501943  7.9785171   0.1560681 ]
-27.375173059883696
None
Score: 30.412742309494
MSE: 63.428425130942635
[-0.0495294   0.01300076 -0.01767035]
28.482940309177604
None
Score: 57.13332413283404
MSE: 36.64713235109741
[-0.30545426 -1.26137391 -0.96006481]
42.86274529093505
None
Score: 56.936409140194534
MSE: 30.721781451181446
[-16.79383444   7.2520459   -1.15478308]
7.5438356383589955
None
Score: -4.198720960563551
MSE: 81.38889027856372
[-0.13805305 -0.77389159 -0.37213288]
38.43739762624689
None
